# manually find these world coordinates from Blender
# the rotations are in XYZ EULER COORDINATES IN DEGREES because that's Blender default
barrelddt1:
  scalefactor: 3.9878
  t: [-0.701382, -0.791855, 15.4895]
  R: [135.421, 0, 0]
  model_path: /Users/jerry/Projects/ms-stuff/barrel-playground/models3d/barrelsingle-scaled.ply
  camposes_path: /Users/jerry/Projects/ms-stuff/barrel-playground/barrels/results/barrelddt1/colmap-out/cam_poses.json
barrel4:
  scalefactor: 1.37754
  t: [-4.55717, 0.819263, 5.44976]
  R: [-47.1032, 2.50546, -28.3796]
  model_path: /Users/jerry/Projects/ms-stuff/barrel-playground/models3d/barrelsingle-scaled.ply
  camposes_path: /Users/jerry/Projects/ms-stuff/barrel-playground/barrels/results/barrel4/colmap-out/cam_poses.json
dive3-depthcharge-03-04:
  scalefactor: 3.40655
  t: [-0.078446, 2.68722, 15.8649]
  R: [-147.863, -20.7501, 98.8496]
  model_path: /Users/jerry/Projects/ms-stuff/barrel-playground/models3d/depth_charge_mark_9_mod_1-scaled.ply
  camposes_path: /Users/jerry/Projects/ms-stuff/barrel-playground/barrels/results/dive3-depthcharge-03-04/colmap-out/cam_poses.json
barrel2:
  scalefactor: 2.48946
  t: [-3.65472, -1.80495, 12.9438]
  R: [33.9378, -11.8677, 9.23124]
  model_path: /Users/jerry/Projects/ms-stuff/barrel-playground/models3d/barrelsingle-scaled.ply
  camposes_path: /Users/jerry/Projects/ms-stuff/barrel-playground/barrels/results/barrel2/colmap-out/cam_poses.json
