# footage info for extracting keyframes and corresponding nav data per frame
default:
  input_path: ~
  output_dir: ~
  start_time: ~
  timezone: US/Pacific
  step: ~
  navpath: ~
  crop: True
  fps: 25
  increase_contrast: False
  denoise_depth: True
  object_name: ~

barrel1:
  input_path: data/dive-data/Dive8/clips/barrel1.mp4
  start_time: 2023-04-14T11:15:24
  step: 25
  navpath: data/dive-data/Dive8/ROV Dive 8 nav.csv
  object_name: barrelsingle-scaled.ply

barrel2:
  input_path: data/dive-data/Dive8/clips/barrel2.mp4
  start_time: 2023-04-14T16:15:58
  step: 25
  navpath: data/dive-data/Dive8/ROV Dive 8 nav.csv
  object_name: barrelsingle-scaled.ply

barrel4:
  input_path: data/dive-data/Dive8/clips/barrel4.mp4
  start_time: 2023-04-14T13:04:49
  step: 25
  navpath: data/dive-data/Dive8/ROV Dive 8 nav.csv
  object_name: barrelsingle-scaled.ply

barrelddt1:
  input_path: data/dive-data/Dive8/clips/barrelddt1.mp4
  start_time: 2023-04-14T14:26:54
  step: 50
  navpath: data/dive-data/Dive8/ROV Dive 8 nav.csv
  object_name: barrelsingle-scaled.ply

dive8-barrel-10-24:
  input_path: data/dive-data/Dive8/clips/dive8-barrel-10-24.mp4
  start_time: 2023-04-14T10:26:41
  step: 50
  navpath: data/dive-data/Dive8/ROV Dive 8 nav.csv
  object_name: barrelsingle-scaled.ply

dive8-barrel-10-45:
  input_path: data/dive-data/Dive8/clips/dive8-barrel-10-45.mp4
  start_time: 2023-04-14T10:46:31
  step: 50
  navpath: data/dive-data/Dive8/ROV Dive 8 nav.csv
  object_name: barrelsingle-scaled.ply

dive3-depthcharge-03-04:
  input_path: data/dive-data/Dive3/clips/dive3-depthcharge-03-04.mp4
  start_time: 2023-04-07T03:04:54
  step: 25
  navpath: data/dive-data/Dive3/ROV Dive 3 nav.csv
  object_name: depth_charge_mark_9_mod_1-scaled.ply

dive3-mousetrap-13-10:
  input_path: data/dive-data/Dive3/clips/dive3-mousetrap-13-10.mp4
  start_time: 2023-04-07T13:10:36
  step: 25
  navpath: data/dive-data/Dive3/ROV Dive 3 nav.csv
  object_name: mousetrap-scaled.ply
